# 创建 GitHub Release 并上传安装包
# 用法: 在 PowerShell 中运行 .\create-release.ps1

$repo = "fangyuuu888-bot/bili-yuqing-assistant"
$tag = "v2.0.0"
$zipPath = "website/bili-yuqing-assistant.zip"

Write-Host "============================================"
Write-Host "  B站舆情分析助手 - GitHub Release 创建工具"
Write-Host "============================================"
Write-Host ""
Write-Host "请按以下步骤操作:"
Write-Host ""
Write-Host "1. 打开 https://github.com/$repo/releases/new"
Write-Host ""
Write-Host "2. 在 'Choose a tag' 输入: $tag"
Write-Host "   点击 'Create new tag: $tag on publish'"
Write-Host ""
Write-Host "3. Release title 输入: B站舆情分析助手 v2.0"
Write-Host ""
Write-Host "4. 点击下方的 'Attach binaries by dropping them here or selecting them'"
Write-Host "   选择文件: $zipPath"
Write-Host "   (完整路径: $(Resolve-Path $zipPath))"
Write-Host ""
Write-Host "5. 点击 'Publish release'"
Write-Host ""
Write-Host "6. 发布完成后，Release 页面会显示下载链接:"
Write-Host "   https://github.com/$repo/releases/download/$tag/bili-yuqing-assistant.zip"
Write-Host ""
Write-Host "7. 把这个链接告诉我，我更新 install.js"
Write-Host ""
Read-Host "按 Enter 键打开浏览器..."

Start-Process "https://github.com/$repo/releases/new"
